{
 "title": "Gatling Report Comparison",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "simulation",
    "query": "SHOW TAG VALUES WITH KEY = \"simulation\" "
   },
   {
    "name": "build1",
    "label": "Recent Build",
    "query": "SHOW TAG VALUES WITH KEY = \"buildNumber\" WHERE \"testName\" =~ /^$simulation$/"
   },
   {
    "name": "build2",
    "label": "Previous Build",
    "query": "SHOW TAG VALUES WITH KEY = \"buildNumber\" WHERE \"testName\" =~ /^$simulation$/"
   },
   {
    "name": "request",
    "query": "SELECT request,last(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND request !~ /^*Slack*/) AND $timeFilter GROUP BY \"request\""
   },
   {
    "name": "baseTime",
    "query": "SELECT \"startTime\" FROM \"autogen\".\"gatling\" WHERE \"buildNumber\" =~ /^$build1$/"
   },
   {
    "name": "finishTime",
    "query": "SELECT \"finishTime\" + $timeFix FROM \"autogen\".\"gatling\" WHERE \"buildNumber\" =~ /^$build1$/"
   },
   {
    "name": "timeShift",
    "query": "SELECT $baseTime - \"startTime\" FROM \"autogen\".\"gatling\" WHERE \"buildNumber\" =~ /^$build2$/"
   },
   {
    "name": "duration1",
    "query": "SELECT \"duration\" FROM \"autogen\".\"gatling\" WHERE \"buildNumber\" =~ /^$build1$/"
   },
   {
    "name": "duration2",
    "query": "SELECT \"duration\" FROM \"autogen\".\"gatling\" WHERE \"buildNumber\" =~ /^$build2$/"
   },
   { "name": "timeFix", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Per Request Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build $build1 | Duration: $duration1",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ok' AND \"request\" =~ /^$request$/ ) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ko' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT mean(\"mean\") AS \"Mean\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 50) AS \"50%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 75) AS \"75%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 95) AS \"95%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 99) AS \"99%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT stddev(\"mean\") AS \"Std.Dev\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT min(\"min\") AS \"Min\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT max(\"max\") AS \"Max\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build $build2 | Duration: $duration2",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ok' AND \"request\" =~ /^$request$/ ) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ko' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT mean(\"mean\") AS \"Mean\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 50) AS \"50%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 75) AS \"75%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 95) AS \"95%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 99) AS \"99%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT stddev(\"mean\") AS \"Std.Dev\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT min(\"min\") AS \"Min\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT max(\"max\") AS \"Max\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all' AND \"request\" =~ /^$request$/) AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Responses Status over Active Users ($request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Build $build1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "OK",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND  \"request\" =~ /^$request$/ AND \"status\" = 'ok') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "KO",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ko') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Active Users",
     "query": "SELECT mean(\"active\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"scenario\" = 'allUsers') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build $build2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "OK",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND  \"request\" =~ /^$request$/ AND \"status\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "KO",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Active Users",
     "query": "SELECT mean(\"active\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"scenario\" = 'allUsers') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Requests Response Time ($request)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Build $build1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "MAX",
     "query": "SELECT mean(\"max\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MEAN",
     "query": "SELECT mean(\"mean\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MIN",
     "query": "SELECT mean(\"min\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND time >= ${baseTime}s AND time <= ${finishTime}s GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Build $build2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "MAX",
     "query": "SELECT mean(\"max\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MEAN",
     "query": "SELECT mean(\"mean\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MIN",
     "query": "SELECT mean(\"min\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}