{
 "title": "Gatling Report Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "simulation", "query": "SHOW MEASUREMENTS" },
   {
    "name": "request",
    "query": "SELECT request,last(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND request !~ /^*Slack*/) AND $timeFilter GROUP BY \"request\""
   }
  ]
 },
 "panels": [
  {
   "title": "Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT sum(\"count\") AS \"OK\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ok') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT sum(\"count\") AS \"KO\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'ko') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT mean(\"mean\") AS \"Mean\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 50) AS \"50%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 75) AS \"75%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 95) AS \"95%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT PERCENTILE(\"mean\", 99) AS \"99%\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT stddev(\"mean\") AS \"Std.Dev\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT min(\"min\") AS \"Min\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "query": "SELECT max(\"max\") AS \"Max\" FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"status\" = 'all') AND $timeFilter GROUP BY \"request\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Responses Status over Active Users ($request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "OK",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND  \"request\" =~ /^$request$/ AND \"status\" = 'ok') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "KO",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'ko') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Active Users",
     "query": "SELECT mean(\"active\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"scenario\" = 'allUsers') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "All Requests Response Time ($request)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "MAX",
     "query": "SELECT mean(\"max\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MEAN",
     "query": "SELECT mean(\"mean\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "MIN",
     "query": "SELECT mean(\"min\") FROM \"autogen\".\"gatling\" WHERE (\"simulation\" =~ /^$simulation$/ AND \"request\" =~ /^$request$/ AND \"status\" = 'all') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors ($request)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "SELECT last(\"requestValue\") AS \"Request\" FROM \"autogen\".\"gatling\" WHERE (\"requestName\" =~ /^$request$/ AND \"testName\" =~ /^$simulation$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "query": "SELECT last(\"value\") AS \"Error\" FROM \"autogen\".\"gatling\" WHERE (\"requestName\" =~ /^$request$/ AND \"testName\" =~ /^$simulation$/) AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}