apiVersion: 1

datasources:
  - name: '$${DS_PROMETHEUS}'
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 5s

  - name: "InfluxDB"
    id: 1
    orgId: 1
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    user: ''
    password: ''
    database: "graphite"
    basicAuth: false
    basicAuthUser: ""
    basicAuthPassword: ""
    withCredentials: false
    isDefault: true
    jsonData: {
      }
    secureJsonFields: null