apiVersion: 1

datasources:
  - name: '$${DS_PROMETHEUS}'
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    version: 1
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s

  - name: 'gatling'
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    isDefault: false
    database: gatling
    user: ''
    password: ''